# Generated by Django 4.2.7 on 2023-12-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestraData', '0003_marcatarjeta_tarjeta_tipotarjeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('cliente', 'cliente')],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('empleado', 'empleado')],
            },
        ),
    ]
