# Generated by Django 4.2.7 on 2023-12-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestraData', '0002_clientesdireccion_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_tarjeta', models.TextField(max_length=120)),
            ],
            options={
                'db_table': 'marca_tarjeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('cvv', models.IntegerField()),
                ('fecha_otorgamiento', models.DateTimeField()),
                ('fecha_exipracion', models.DateTimeField()),
            ],
            options={
                'db_table': 'tarjeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tarjeta', models.TextField(max_length=150)),
            ],
            options={
                'db_table': 'tipo_tarjeta',
                'managed': False,
            },
        ),
    ]
